#!/bin/bash


#Create a session for local services
LOCAL_TOKEN=$( grep -q de.openschoolserver.api.auth.localhost= /opt/oss-java/conf/oss-api.properties )
if [ -z "${LOCAL_TOKEN}" -o ${SCHOOL_RESET_REGISTER_PASSWORD} = "yes" ]; then
	grep -q de.openschoolserver.api.auth.localhost= /opt/oss-java/conf/oss-api.properties || echo de.openschoolserver.api.auth.localhost=TOKEN >> /opt/oss-java/conf/oss-api.properties
	TOKEN="localhost_"$(uuidgen)
	sed -i s/de.openschoolserver.api.auth.localhost=.*/de.openschoolserver.api.auth.localhost=$TOKEN/ /opt/oss-java/conf/oss-api.properties
	chmod 600            /opt/oss-java/conf/oss-api.properties
	SQLUSER=$( grep javax.persistence.jdbc.user= /opt/oss-java/conf/oss-api.properties | sed 's/javax.persistence.jdbc.user=//' )
	SQLPW=$( grep javax.persistence.jdbc.password= /opt/oss-java/conf/oss-api.properties | sed 's/javax.persistence.jdbc.password=//' )
	echo "DELETE FROM Sessions WHERE IP='127.0.0.1'" | mysql -u $SQLUSER -p${SQLPW} OSS
	echo "INSERT INTO Sessions VALUES(NULL,1,NULL,NULL,NOW(),'127.0.0.1','$TOKEN')" | mysql -u $SQLUSER -p${SQLPW} OSS
fi
#Create recreate the printer driver files if neccesarry
if [ -e /usr/share/oss/templates/printers.txt -a -e /usr/share/oss/templates/drivers.txt ]; then
        NEWER=$( find /usr/share/cups -name '*ppd.gz' -newer /usr/share/oss/templates/printers.txt )
        if [ "$NEWER" ]; then
                /usr/share/oss/tools/CreatePrinterPpd.pl
        fi
else
        /usr/share/oss/tools/CreatePrinterPpd.pl
fi

#Register the server if not already done
if [ ! -e /etc/zypp/repos.d/OSS.repo -o ! -e /srv/salt/repos.d/salt-packages.repo ]; then
        /usr/share/oss/tools/register.sh
fi

#Create lock dir if not exists
if [ -d /run/lock/oss-api ]; then
        mkdir -p /run/lock/oss-api
fi

#Restart some scripts
SQUIDACTIVE=$(  systemctl is-active squid.service )
SQUIDENABLED=$(  systemctl is-enabled squid.service )
if [ "$SQUIDACTIVE" = "active" -a "$SQUIDENABLED" = "enabled" ]; then
        setfacl -m u:squid:r /opt/oss-java/conf/oss-api.properties
        systemctl restart squid.service
fi

#Java path
APP_HOME="/opt/oss-java"

@CLASSPATH@

exec java -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp $CLASSPATH de.openschoolserver.api.ServerApplication server /opt/oss-java/conf/config.yml >> /var/log/oss-api.log 2>&1

